---
title: "Week 2021/20 US Broadband"
output: github_document
---

```{r load-and-import, echo=TRUE, message=FALSE, warning=FALSE}
extrafont::loadfonts(device = "win")

library(sf) # Mapping
library(tigris) # Mapping
options(tigris_use_cache = TRUE)
options(tigris_class = "sf")

library(tidyverse)
library(here)
library(colorspace)
library(ggtext)

raw_df <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-11/broadband.csv")
raw_df
```

```{r}
# Import county shapefiles
county_maps <- read_sf(here("2021/2021_05_11/county/"))

# Combine shapefiles with our original data
combined_df <-
county_maps %>%
  left_join(
    raw_df %>%
      janitor::clean_names() %>%
      mutate(
        COUNTYFP = as.character(county_id) %>% str_sub(., -3),
        STATEFP = as.character(county_id) %>% str_remove(string = ., pattern = ".{3}$") %>% str_pad(width = 2, side = "left", pad = "0")
      ),
    by = c("STATEFP", "COUNTYFP")
  )
```

```{r broadband-usage-illinois-surrounding-states, fig.height = 7, fig.width = 5}

combined_df %>%
  mutate(broadband_availability_per_fcc = as.numeric(broadband_availability_per_fcc),
         broadband_usage = as.numeric(broadband_usage)) %>%
  filter(st %in% c("IL", "WI", "MI", "IN")) %>%
  ggplot() +
  geom_sf(aes(geometry = geometry, fill = broadband_usage*100), colour = "grey90") +
  geom_sf(data = . %>% group_by(st) %>% summarise(), colour = "grey15", fill = NA) +
  coord_sf(crs = 4326, 
           expand = TRUE,
           clip = "off") +
  scale_fill_continuous_sequential(
    palette = "Inferno",
    name = "Broadband usage (%)",
    na.value = "grey90",
    labels = scales::label_number(accuracy = 1),
    guide = guide_colorbar(
     barwidth = unit(5, "cm"),
     frame.colour = "black",
     frame.linewidth = 1,
     frame.linetype = 1,
     draw.llim = FALSE,
     draw.ulim = FALSE
    )
  ) +
  annotate(geom = "text", x = -92, y = 38, label = "Illinois") +
  annotate(geom = "text", x = -83.5, y = 39, label = "Indiana") +
  annotate(geom = "text", x = -82, y = 45, label = "Michigan") +
  annotate(geom = "text", x = -93, y = 43, label = "Wisconsin") +
  labs(
    title = "**Broadband usage** in Illinois and neighbouring states"
  ) +
  ggthemes::theme_map() +
  theme(
    legend.position = "bottom",
    strip.background = element_blank(),
    panel.spacing = unit(0.5, "lines"),
    plot.title = element_markdown(hjust = 0.5, size = 15)
  )
  
```

