---
title: "Week 2020/02: Australian Fires"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
extrafont::loadfonts(device="win")
#extrafont::fonttable()
#extrafont::font_import("C:/Windows/Fonts/", pattern = "RobotoCondensed")

library(tidyverse)
library(lubridate)
library(ggtext)
```

```{r import}
raw_df <- tidytuesdayR::tt_load(2020, week = 2)
raw_temp <- raw_df$temperature
raw_rain <- raw_df$rainfall
raw_fires <- raw_df$fire_nrt_M6_94771
```
Needs work:

```{r dpi = 300, fig.height = 5, fig.width = 10}
data <-
raw_fires %>%
  filter(confidence > 80) %>%
  mutate(date_time = ymd_hm(paste(acq_date, acq_time))) %>%
  select(date_time, everything()) %>%
  count(date_time) 



p <-
  ggplot() +
  geom_col(data = data, aes(x = date_time, y = n, colour = log(n), fill = log(n))) +
  coord_cartesian(ylim = c(0, 1)) +
  colorspace::scale_color_continuous_sequential(palette = "Inferno") +
  colorspace::scale_fill_continuous_sequential(palette = "Inferno") +
  guides(
    fill = FALSE,
    colour = FALSE
  ) +
  theme_void() +
  theme(
    plot.margin = margin(20, 20, 20, 20),
    plot.background = element_rect(fill = "#000000")
  )

title_df <-
  data.frame(
        xmin = ymd_hms("2019-11-03 01:20:00"),
        xmax = ymd_hms("2019-11-27 01:20:00"),
        ymin = c(0.1),
        ymax = c(0.5),
        x = ymd_hms("2019-11-03 01:20:00"),
        y = 0.17,
        label = "<span style='font-size:24pt'>**Australian Wildfires**</span><br><span style='font-size:10pt'>**Incidences of wildfires from Nov 2019 through Jan 2020**</span>")
   

p +
  geom_rect(
    data = title_df,
    aes(
    xmin = xmin, 
    xmax = xmax, 
    ymin = ymin, 
    ymax = ymax,
    ),
    fill = "#FFFFFF", 
    colour = NA, 
    alpha = 1) +
  geom_richtext(
    data = title_df,
    aes(
      x = x,
      y = y,
      hjust = 0,
      label = label
    ),
    fill = NA,
    label.colour = NA,
    family = "Roboto Condensed",
    colour = "black"
  )
  
```


